site_name: Leeds Beckett Template

theme:
  name: readthedocs

extra_css:
  - css/extra.css

plugins:
  - autorefs
  - glightbox
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            heading_level: 2
            separate_signature: True
            docstring_section_style: list
            show_root_heading: True
            show_signature_annotations: True
            show_category_heading: True
            show_source: True
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
  - search

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: 'index.md'

watch:
  - src
